name: Release to TEST PyPI
on:
  push:
    tags: ["test-*"] # test-1.0.0 trigger to deploy on test pypi while release-1.0.0 is on production pypi

env:
  dists-artifact-name: python-package-distributions
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure tag is from main branch
        run: |
          if ! git merge-base --is-ancestor origin/main $GITHUB_SHA; then
            echo "Tag commit is not on main branch. Skipping release."
            exit 1
          fi
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 #@v7
        # https://github.com/astral-sh/setup-uv/tags
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: uv build --python 3.13 --python-preference only-managed --sdist --wheel . --out-dir dist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4 
        with:
          name: ${{ env.dists-artifact-name }}
          path: dist/*

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/multimodaltranslation  # see https://test.pypi.org/manage/account/publishing

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
      with:
        verbose: true
        repository-url: https://test.pypi.org/legacy/
